version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: contrap_postgres
    environment:
      POSTGRES_DB: contrap
      POSTGRES_USER: contrap_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-contrap_dev_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U contrap_user -d contrap"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - contrap_network

  redis:
    image: redis:7-alpine
    container_name: contrap_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - contrap_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: contrap_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@contrap.pt
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - contrap_network

volumes:
  postgres_data:
  redis_data:

networks:
  contrap_network:
    driver: bridge
